### ISSUE TITLE
tests don't compile on ghc 9.2.2

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/vector#432]
I get compile errors of the test code when running the tests on ghc 9.2.2, e.g.:
```
[ 5 of 12] Compiling Tests.Vector.Unboxed ( tests/Tests/Vector/Unboxed.hs, /Users/gcolpitts/haskell/vector-0.12.3.1/dist-newstyle/build/x86_64-osx/ghc-9.2.2/vector-0.12.3.1/t/vector-tests-O2/build/vector-tests-O2/vector-tests-O2-tmp/Tests/Vector/Unboxed.o, /Users/gcolpitts/haskell/vector-0.12.3.1/dist-newstyle/build/x86_64-osx/ghc-9.2.2/vector-0.12.3.1/t/vector-tests-O2/build/vector-tests-O2/vector-tests-O2-tmp/Tests/Vector/Unboxed.dyn_o )

Data/Vector/Storable/Mutable.hs:285:10: error:
    • Couldn't match kind ‘k’ with ‘*’
      When matching types
        v13 :: * -> * -> *
        MVector :: k -> * -> *
      Expected: MVector s a -> Int
        Actual: v13 s13 a -> Int
      ‘k’ is a rigid type variable bound by
        the type signature for:
          length :: forall {k} a (s :: k). Storable a => MVector s a -> Int
        at Data/Vector/Storable/Mutable.hs:283:1-42
    • In the expression: G.length
      In an equation for ‘length’: length = G.length
    • Relevant bindings include
        length :: MVector s a -> Int
          (bound at Data/Vector/Storable/Mutable.hs:285:1)
```

```
The above happened after I did:
```
cabal get vector
cd vector*
cabal v2-test
```

Version info:
```
 ghc --version
ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.2
gcolpitts@macMini-2018 vector-0.12.3.1 % cabal --version
cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
```

**Comment by konsumlamm** [comment]
The tests run fine for me on latest `master`, so this seems to have been fixed in the meantime.

**Comment by GeorgeCo** [comment]
Thx, good news! I'm going to close then
