### ISSUE TITLE
`-fdefer-typed-holes` breaks the build

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/vector#200]
I'm very confused by this behavior. It's possibly a GHC bug. Compiling with e.g.
```
cabal new-build -O0 --ghc-options=-fdefer-typed-holes
```
gives many errors like
```
internal/unbox-tuple-instances:1118:53: error:
    • Could not deduce (G.Vector Vector f)
        arising from a use of ‘G.stream’
      from the context: G.Vector Vector (a, b, c, d, e, f)
        bound by the RULE "stream/zip6 [Vector.Unboxed]"
        at internal/unbox-tuple-instances:(1107,11)-(1118,64)
    • In the 7th argument of ‘Bundle.zipWith6’, namely ‘(G.stream fs)’
      In the expression:
        Bundle.zipWith6
          (,,,,,)
          (G.stream as)
          (G.stream bs)
          (G.stream cs)
          (G.stream ds)
          (G.stream es)
          (G.stream fs)
      When checking the transformation rule "stream/zip6 [Vector.Unboxed]"
```

**Comment by RyanGlScott** [comment]
Minimal example:

```haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE MultiParamTypeClasses #-}
module Bug where

import Prelude hiding (zip, zipWith)

zipWith :: (a -> b -> c)
        -> Bundle v a
        -> Bundle v b
        -> Bundle v c
zipWith = undefined

class GVector (v :: * -> *) a
instance GVector Vector a

data Bundle (v :: * -> *) a
data Vector a
class Unbox a

stream :: GVector v a => v a -> Bundle v a
{-# INLINE [1] stream #-}
stream = undefined

zip :: (Unbox a, Unbox b) => Vector a -> Vector b -> Vector (a, b)
{-# INLINE [1] zip #-}
zip = undefined
{-# RULES "stream/zip [Vector.Unboxed]" forall as bs .
  stream (zip as bs) = zipWith (,) (stream as)
                                   (stream bs)   #-}
```
```
$ /opt/ghc/8.2.2/bin/ghc -fforce-recomp Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )
$ /opt/ghc/8.2.2/bin/ghc -fforce-recomp Bug.hs -fdefer-typed-holes
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )

Bug.hs:29:11: error:
    • Could not deduce (Unbox a) arising from a use of ‘zip’
      from the context: GVector Vector (a, b)
        bound by the RULE "stream/zip [Vector.Unboxed]"
        at Bug.hs:(28,11)-(30,46)
      Possible fix:
        add (Unbox a) to the context of
          the RULE "stream/zip [Vector.Unboxed]"
    • In the first argument of ‘stream’, namely ‘(zip as bs)’
      In the expression: stream (zip as bs)
      When checking the transformation rule "stream/zip [Vector.Unboxed]"
   |
29 |   stream (zip as bs) = zipWith (,) (stream as)
   |           ^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
It seems that this is a GHC regression that was introduced between 7.10.3 (where the above program works with `-fdefer-typed-holes`) and 8.0.1 (where it does not).

@mitchellwrosen, do you want to open the Trac ticket? :)

**Comment by mitchellwrosen** [comment]
@RyanGlScott Of course and thanks for looking into it!

**Comment by mitchellwrosen** [comment]
https://ghc.haskell.org/trac/ghc/ticket/14732

**Comment by RyanGlScott** [comment]
Trac #14732 has been fixed upstream.
